### PR TITLE
QuotePDF Updates

### PR DESCRIPTION
**Pull request by neilk17**

### CODE REVIEW

**Comment by barbinbrad** [comment]
Can we add the custom information to the top?

**Comment by neilk17** [comment]
> Can we add the custom information to the top?

Yes, can do that now

**Comment by neilk17** [comment]
Screenshot 2024-03-20 at 11 39 44 PM

**Review by barbinbrad — APPROVED** [review]
Looks great! Feel free to merge. 

I'd like to see more contact information in the Quote PDF (fetched through a view) and the "Release" button disabled when the status is not draft. But overall looks great, and we can definitely tackle that in follow-on work.

**Pull request merged**
